service: custom-scraping

provider:
  environment:
    ENV: ${self:provider.stage}
  name: aws
  region: eu-north-1
  runtime: python3.11
  stage: ${opt:stage, "dev"}

functions:
  scraper:
    memorySize: 256
    timeout: 60
    image:
      uri: 863518458210.dkr.ecr.eu-north-1.amazonaws.com/custom-scraping-python:latest
      command:
        - scrapers/scraper.handler
      events:
        - schedule: rate(1 day)